# Generated by Django 3.2.7 on 2021-09-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgurl', models.URLField()),
                ('title', models.CharField(max_length=100)),
                ('runtime', models.CharField(max_length=50)),
                ('medium', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('watched', models.BooleanField(default=False)),
                ('notes', models.CharField(max_length=255)),
            ],
        ),
    ]
