# Generated by Django 3.2.7 on 2021-09-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='genre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='movies',
            name='imgurl',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='medium',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='movies',
            name='notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='movies',
            name='runtime',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='movies',
            name='source',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='movies',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
